version: '3'
services:
    mongo:
        image: mongo:3.6
        volumes:
            - mongo-data:/data/db
        command: mongod --port 27018
        ports:
            - '27018:27018'
        networks:
            - myapp
        #network_mode: host
    commutag:
        #image: aga3134/commutag:1.5.2
        build:
            context: ./
            dockerfile: Dockerfile
            target: test
        volumes:
            - ./config.json:/CommuTag/config.json
            - ./log:/CommuTag/log
            - ./static/upload:/CommuTag/static/upload
            - ./static/file:/CommuTag/static/file
        ports:
            - "8011:8011"
        depends_on:
            - mongo
        networks:
            - myapp
        #network_mode: host
volumes:
    mongo-data:
networks:
    myapp:
        driver: bridge
